# Define stages for the CI/CD pipeline
stages:
  - build
  - test
  - deploy
  - security

# --- BUILD STAGE ---
# Build your backend Docker image if needed
build-backend:
  stage: build
  image: node:16
  script:
    - npm install  # Install dependencies
    - npm run build # Build the application (e.g., transpile TypeScript)
  artifacts:
    paths:
      - build/    # Store build artifacts for subsequent jobs

# --- TEST STAGE ---
# Run unit tests and integration tests
test-backend:
  stage: test
  image: node:16
  script:
    - npm install   # Install dependencies
    - npm run test  # Run tests (ensure you have test scripts defined in package.json)
  coverage: '/Total coverage: \d+\.\d+/'  # (Optional) Specify coverage regex for the code quality

# --- SECURITY STAGE ---
# Include SAST and other security scanning templates
sast:
  stage: security
  include:
    - template: Security/SAST.gitlab-ci.yml

# --- DEPLOY STAGE ---
# Deploy the application to your server or cloud
deploy-backend:
  stage: deploy
  script:
    - echo "Deploying backend..."
    - docker build -t backend-image . # Docker build command if you're using Docker
    - docker push backend-image        # Push to Docker registry (if applicable)
  only:
    - main  # Only deploy on the main branch
